name: Build CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: buildjet-64vcpu-ubuntu-2204

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update -q
        sudo apt-get install -y -q \
          gcc-aarch64-linux-gnu \
          gcc-arm-linux-gnueabi \
          libarchive-tools \
          build-essential \
          libncurses-dev \
          bison \
          flex \
          libssl-dev \
          binutils \
          python3 \
          ccache

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
