name: Build CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: buildjet-32vcpu-ubuntu-2204

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone Kernel
        uses: actions/checkout@v4
        with:
          repository: y82t2z/WaifuKernel-F3
          path: kernel/kernel_xiaomi_sm8250
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
