name: Build CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone Kernel
        uses: actions/checkout@v3
        with:
          repository: y82t2z/xiaomi_sm8250_kernel
          path: kernel
      
      - name: Download Clang
        run: |
           chmod +x download-clang.sh
           bash download-clang.sh